import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# enter the path to be used for data used and generated by this script
path = '../Data/'
dataset = 'Weighted_Content_twitter_vectors_byWeek_date!.csv'

# read in the data and create dataframe, drop unused columns, then pickle
dfw = pd.read_csv(path+dataset)
dfw.drop(columns=(dfw.columns[2252:]), inplace=True)
dfw.set_index('new_date', inplace=True)
dfw.to_pickle(path+'dfw_final.pkl')

# create train and test sets, then pickle
train_set, test_set = train_test_split(dfw, test_size=0.2, random_state=42)
X_train = train_set.drop('TARGET', axis=1)
y_train = train_set['TARGET']

X_test = test_set.drop('TARGET', axis=1)
y_test = test_set['TARGET']

X_train.to_pickle(path+'X_train.pkl')
y_train.to_pickle(path+'y_train.pkl')
X_test.to_pickle(path+'X_test.pkl')
y_test.to_pickle(path+'y_test.pkl')
